            sed -i '' 's/targetCompatibility = [0-9.]*/targetCompatibility = JavaVersion.VERSION_21/g' "$f"
            sed -i '' 's/compileSdkVersion [0-9]*/compileSdkVersion 35/g' "$f"
            sed -i '' 's/compileSdk = [0-9]*/compileSdk = 35/g' "$f"
            sed -i '' 's/targetSdkVersion [0-9]*/targetSdkVersion 35/g' "$f"
            sed -i '' 's/targetSdk = [0-9]*/targetSdk = 35/g' "$f"
          done
      - name: Build APK
        script: |
          cd android
          ./gradlew clean assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
